### ISSUE TITLE
Thank you for the template

### ISSUE THREAD

**Issue by DealsBeam** [bagoes/bgsstyles#1]
Thanks for the template, can you release englsih version please?

**Comment by bagoes** [comment]
> Thanks for the template, can you release englsih version please?

I will consider, while you can translate yourself from Indonesian if you want.

**Comment by bagoes** [comment]
Now update with English

**Comment by DealsBeam** [comment]
Thank you, this is one of the best blogspot / blogger templates, do you have any plans to update it to the latest bootstrap version? thank you once again.
